one_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: one_joint
    joint_speed: 1.0
    motor:
        id: 1
        init: 512
        min: 0
        max: 1023

two_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: two_joint
    joint_speed: 1.0
    motor:
        id: 2
        init: 512
        min: 0
        max: 1023

three_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: three_joint
    joint_speed: 1.0
    motor:
        id: 3
        init: 512
        min: 0
        max: 1023

four_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: four_joint
    joint_speed: 1.0
    motor:
        id: 4
        init: 512
        min: 0
        max: 1023

five_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: five_joint
    joint_speed: 1.0
    motor:
        id: 5
        init: 512
        min: 0
        max: 1023
